// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/git_config.proto

package contracts.v1;

public final class GitConfigOuterClass {
  private GitConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GitConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:contracts.v1.GitConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string repo_source = 1;</code>
     */
    java.lang.String getRepoSource();
    /**
     * <code>string repo_source = 1;</code>
     */
    com.google.protobuf.ByteString
        getRepoSourceBytes();

    /**
     * <code>string repo_owner = 2;</code>
     */
    java.lang.String getRepoOwner();
    /**
     * <code>string repo_owner = 2;</code>
     */
    com.google.protobuf.ByteString
        getRepoOwnerBytes();

    /**
     * <code>string repo_name = 3;</code>
     */
    java.lang.String getRepoName();
    /**
     * <code>string repo_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getRepoNameBytes();

    /**
     * <code>string repo_branch = 4;</code>
     */
    java.lang.String getRepoBranch();
    /**
     * <code>string repo_branch = 4;</code>
     */
    com.google.protobuf.ByteString
        getRepoBranchBytes();

    /**
     * <code>string repo_revision = 5;</code>
     */
    java.lang.String getRepoRevision();
    /**
     * <code>string repo_revision = 5;</code>
     */
    com.google.protobuf.ByteString
        getRepoRevisionBytes();
  }
  /**
   * Protobuf type {@code contracts.v1.GitConfig}
   */
  public  static final class GitConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:contracts.v1.GitConfig)
      GitConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GitConfig.newBuilder() to construct.
    private GitConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GitConfig() {
      repoSource_ = "";
      repoOwner_ = "";
      repoName_ = "";
      repoBranch_ = "";
      repoRevision_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GitConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              repoSource_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              repoOwner_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              repoName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              repoBranch_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              repoRevision_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contracts.v1.GitConfigOuterClass.internal_static_contracts_v1_GitConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contracts.v1.GitConfigOuterClass.internal_static_contracts_v1_GitConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              contracts.v1.GitConfigOuterClass.GitConfig.class, contracts.v1.GitConfigOuterClass.GitConfig.Builder.class);
    }

    public static final int REPO_SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object repoSource_;
    /**
     * <code>string repo_source = 1;</code>
     */
    public java.lang.String getRepoSource() {
      java.lang.Object ref = repoSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoSource_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRepoSourceBytes() {
      java.lang.Object ref = repoSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_OWNER_FIELD_NUMBER = 2;
    private volatile java.lang.Object repoOwner_;
    /**
     * <code>string repo_owner = 2;</code>
     */
    public java.lang.String getRepoOwner() {
      java.lang.Object ref = repoOwner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoOwner_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_owner = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRepoOwnerBytes() {
      java.lang.Object ref = repoOwner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object repoName_;
    /**
     * <code>string repo_name = 3;</code>
     */
    public java.lang.String getRepoName() {
      java.lang.Object ref = repoName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoName_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRepoNameBytes() {
      java.lang.Object ref = repoName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_BRANCH_FIELD_NUMBER = 4;
    private volatile java.lang.Object repoBranch_;
    /**
     * <code>string repo_branch = 4;</code>
     */
    public java.lang.String getRepoBranch() {
      java.lang.Object ref = repoBranch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoBranch_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_branch = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRepoBranchBytes() {
      java.lang.Object ref = repoBranch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoBranch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_REVISION_FIELD_NUMBER = 5;
    private volatile java.lang.Object repoRevision_;
    /**
     * <code>string repo_revision = 5;</code>
     */
    public java.lang.String getRepoRevision() {
      java.lang.Object ref = repoRevision_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoRevision_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_revision = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRepoRevisionBytes() {
      java.lang.Object ref = repoRevision_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoRevision_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRepoSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, repoSource_);
      }
      if (!getRepoOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, repoOwner_);
      }
      if (!getRepoNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, repoName_);
      }
      if (!getRepoBranchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, repoBranch_);
      }
      if (!getRepoRevisionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, repoRevision_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRepoSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, repoSource_);
      }
      if (!getRepoOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, repoOwner_);
      }
      if (!getRepoNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, repoName_);
      }
      if (!getRepoBranchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, repoBranch_);
      }
      if (!getRepoRevisionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, repoRevision_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof contracts.v1.GitConfigOuterClass.GitConfig)) {
        return super.equals(obj);
      }
      contracts.v1.GitConfigOuterClass.GitConfig other = (contracts.v1.GitConfigOuterClass.GitConfig) obj;

      boolean result = true;
      result = result && getRepoSource()
          .equals(other.getRepoSource());
      result = result && getRepoOwner()
          .equals(other.getRepoOwner());
      result = result && getRepoName()
          .equals(other.getRepoName());
      result = result && getRepoBranch()
          .equals(other.getRepoBranch());
      result = result && getRepoRevision()
          .equals(other.getRepoRevision());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPO_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getRepoSource().hashCode();
      hash = (37 * hash) + REPO_OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getRepoOwner().hashCode();
      hash = (37 * hash) + REPO_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRepoName().hashCode();
      hash = (37 * hash) + REPO_BRANCH_FIELD_NUMBER;
      hash = (53 * hash) + getRepoBranch().hashCode();
      hash = (37 * hash) + REPO_REVISION_FIELD_NUMBER;
      hash = (53 * hash) + getRepoRevision().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.GitConfigOuterClass.GitConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(contracts.v1.GitConfigOuterClass.GitConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contracts.v1.GitConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:contracts.v1.GitConfig)
        contracts.v1.GitConfigOuterClass.GitConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return contracts.v1.GitConfigOuterClass.internal_static_contracts_v1_GitConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return contracts.v1.GitConfigOuterClass.internal_static_contracts_v1_GitConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                contracts.v1.GitConfigOuterClass.GitConfig.class, contracts.v1.GitConfigOuterClass.GitConfig.Builder.class);
      }

      // Construct using contracts.v1.GitConfigOuterClass.GitConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        repoSource_ = "";

        repoOwner_ = "";

        repoName_ = "";

        repoBranch_ = "";

        repoRevision_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return contracts.v1.GitConfigOuterClass.internal_static_contracts_v1_GitConfig_descriptor;
      }

      @java.lang.Override
      public contracts.v1.GitConfigOuterClass.GitConfig getDefaultInstanceForType() {
        return contracts.v1.GitConfigOuterClass.GitConfig.getDefaultInstance();
      }

      @java.lang.Override
      public contracts.v1.GitConfigOuterClass.GitConfig build() {
        contracts.v1.GitConfigOuterClass.GitConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public contracts.v1.GitConfigOuterClass.GitConfig buildPartial() {
        contracts.v1.GitConfigOuterClass.GitConfig result = new contracts.v1.GitConfigOuterClass.GitConfig(this);
        result.repoSource_ = repoSource_;
        result.repoOwner_ = repoOwner_;
        result.repoName_ = repoName_;
        result.repoBranch_ = repoBranch_;
        result.repoRevision_ = repoRevision_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof contracts.v1.GitConfigOuterClass.GitConfig) {
          return mergeFrom((contracts.v1.GitConfigOuterClass.GitConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(contracts.v1.GitConfigOuterClass.GitConfig other) {
        if (other == contracts.v1.GitConfigOuterClass.GitConfig.getDefaultInstance()) return this;
        if (!other.getRepoSource().isEmpty()) {
          repoSource_ = other.repoSource_;
          onChanged();
        }
        if (!other.getRepoOwner().isEmpty()) {
          repoOwner_ = other.repoOwner_;
          onChanged();
        }
        if (!other.getRepoName().isEmpty()) {
          repoName_ = other.repoName_;
          onChanged();
        }
        if (!other.getRepoBranch().isEmpty()) {
          repoBranch_ = other.repoBranch_;
          onChanged();
        }
        if (!other.getRepoRevision().isEmpty()) {
          repoRevision_ = other.repoRevision_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        contracts.v1.GitConfigOuterClass.GitConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (contracts.v1.GitConfigOuterClass.GitConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object repoSource_ = "";
      /**
       * <code>string repo_source = 1;</code>
       */
      public java.lang.String getRepoSource() {
        java.lang.Object ref = repoSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRepoSourceBytes() {
        java.lang.Object ref = repoSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_source = 1;</code>
       */
      public Builder setRepoSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_source = 1;</code>
       */
      public Builder clearRepoSource() {
        
        repoSource_ = getDefaultInstance().getRepoSource();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_source = 1;</code>
       */
      public Builder setRepoSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoOwner_ = "";
      /**
       * <code>string repo_owner = 2;</code>
       */
      public java.lang.String getRepoOwner() {
        java.lang.Object ref = repoOwner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoOwner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_owner = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRepoOwnerBytes() {
        java.lang.Object ref = repoOwner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoOwner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_owner = 2;</code>
       */
      public Builder setRepoOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoOwner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_owner = 2;</code>
       */
      public Builder clearRepoOwner() {
        
        repoOwner_ = getDefaultInstance().getRepoOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_owner = 2;</code>
       */
      public Builder setRepoOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoOwner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoName_ = "";
      /**
       * <code>string repo_name = 3;</code>
       */
      public java.lang.String getRepoName() {
        java.lang.Object ref = repoName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRepoNameBytes() {
        java.lang.Object ref = repoName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_name = 3;</code>
       */
      public Builder setRepoName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_name = 3;</code>
       */
      public Builder clearRepoName() {
        
        repoName_ = getDefaultInstance().getRepoName();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_name = 3;</code>
       */
      public Builder setRepoNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoBranch_ = "";
      /**
       * <code>string repo_branch = 4;</code>
       */
      public java.lang.String getRepoBranch() {
        java.lang.Object ref = repoBranch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoBranch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_branch = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRepoBranchBytes() {
        java.lang.Object ref = repoBranch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoBranch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_branch = 4;</code>
       */
      public Builder setRepoBranch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoBranch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_branch = 4;</code>
       */
      public Builder clearRepoBranch() {
        
        repoBranch_ = getDefaultInstance().getRepoBranch();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_branch = 4;</code>
       */
      public Builder setRepoBranchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoBranch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoRevision_ = "";
      /**
       * <code>string repo_revision = 5;</code>
       */
      public java.lang.String getRepoRevision() {
        java.lang.Object ref = repoRevision_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoRevision_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_revision = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRepoRevisionBytes() {
        java.lang.Object ref = repoRevision_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoRevision_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_revision = 5;</code>
       */
      public Builder setRepoRevision(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoRevision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_revision = 5;</code>
       */
      public Builder clearRepoRevision() {
        
        repoRevision_ = getDefaultInstance().getRepoRevision();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_revision = 5;</code>
       */
      public Builder setRepoRevisionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoRevision_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:contracts.v1.GitConfig)
    }

    // @@protoc_insertion_point(class_scope:contracts.v1.GitConfig)
    private static final contracts.v1.GitConfigOuterClass.GitConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new contracts.v1.GitConfigOuterClass.GitConfig();
    }

    public static contracts.v1.GitConfigOuterClass.GitConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GitConfig>
        PARSER = new com.google.protobuf.AbstractParser<GitConfig>() {
      @java.lang.Override
      public GitConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GitConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GitConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GitConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public contracts.v1.GitConfigOuterClass.GitConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contracts_v1_GitConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contracts_v1_GitConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035contracts.v1/git_config.proto\022\014contrac" +
      "ts.v1\"s\n\tGitConfig\022\023\n\013repo_source\030\001 \001(\t\022" +
      "\022\n\nrepo_owner\030\002 \001(\t\022\021\n\trepo_name\030\003 \001(\t\022\023" +
      "\n\013repo_branch\030\004 \001(\t\022\025\n\rrepo_revision\030\005 \001" +
      "(\tBAZ?github.com/estafette/estafette-ci-" +
      "contracts-golang/contracts_v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_contracts_v1_GitConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contracts_v1_GitConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contracts_v1_GitConfig_descriptor,
        new java.lang.String[] { "RepoSource", "RepoOwner", "RepoName", "RepoBranch", "RepoRevision", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
