// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/list_response.proto

package contracts.v1;

public final class ListResponseOuterClass {
  private ListResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:contracts.v1.ListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getItemsList();
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    com.google.protobuf.Any getItems(int index);
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    boolean hasPagination();
    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    contracts.v1.PaginationOuterClass.Pagination getPagination();
    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    contracts.v1.PaginationOuterClass.PaginationOrBuilder getPaginationOrBuilder();
  }
  /**
   * Protobuf type {@code contracts.v1.ListResponse}
   */
  public  static final class ListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:contracts.v1.ListResponse)
      ListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListResponse.newBuilder() to construct.
    private ListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListResponse() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            case 18: {
              contracts.v1.PaginationOuterClass.Pagination.Builder subBuilder = null;
              if (pagination_ != null) {
                subBuilder = pagination_.toBuilder();
              }
              pagination_ = input.readMessage(contracts.v1.PaginationOuterClass.Pagination.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pagination_);
                pagination_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contracts.v1.ListResponseOuterClass.internal_static_contracts_v1_ListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contracts.v1.ListResponseOuterClass.internal_static_contracts_v1_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              contracts.v1.ListResponseOuterClass.ListResponse.class, contracts.v1.ListResponseOuterClass.ListResponse.Builder.class);
    }

    private int bitField0_;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.Any> items_;
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    public java.util.List<com.google.protobuf.Any> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    public com.google.protobuf.Any getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any items = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int PAGINATION_FIELD_NUMBER = 2;
    private contracts.v1.PaginationOuterClass.Pagination pagination_;
    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    public boolean hasPagination() {
      return pagination_ != null;
    }
    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    public contracts.v1.PaginationOuterClass.Pagination getPagination() {
      return pagination_ == null ? contracts.v1.PaginationOuterClass.Pagination.getDefaultInstance() : pagination_;
    }
    /**
     * <code>.contracts.v1.Pagination pagination = 2;</code>
     */
    public contracts.v1.PaginationOuterClass.PaginationOrBuilder getPaginationOrBuilder() {
      return getPagination();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      if (pagination_ != null) {
        output.writeMessage(2, getPagination());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      if (pagination_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPagination());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof contracts.v1.ListResponseOuterClass.ListResponse)) {
        return super.equals(obj);
      }
      contracts.v1.ListResponseOuterClass.ListResponse other = (contracts.v1.ListResponseOuterClass.ListResponse) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && (hasPagination() == other.hasPagination());
      if (hasPagination()) {
        result = result && getPagination()
            .equals(other.getPagination());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (hasPagination()) {
        hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
        hash = (53 * hash) + getPagination().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.ListResponseOuterClass.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(contracts.v1.ListResponseOuterClass.ListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contracts.v1.ListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:contracts.v1.ListResponse)
        contracts.v1.ListResponseOuterClass.ListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return contracts.v1.ListResponseOuterClass.internal_static_contracts_v1_ListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return contracts.v1.ListResponseOuterClass.internal_static_contracts_v1_ListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                contracts.v1.ListResponseOuterClass.ListResponse.class, contracts.v1.ListResponseOuterClass.ListResponse.Builder.class);
      }

      // Construct using contracts.v1.ListResponseOuterClass.ListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        if (paginationBuilder_ == null) {
          pagination_ = null;
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return contracts.v1.ListResponseOuterClass.internal_static_contracts_v1_ListResponse_descriptor;
      }

      @java.lang.Override
      public contracts.v1.ListResponseOuterClass.ListResponse getDefaultInstanceForType() {
        return contracts.v1.ListResponseOuterClass.ListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public contracts.v1.ListResponseOuterClass.ListResponse build() {
        contracts.v1.ListResponseOuterClass.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public contracts.v1.ListResponseOuterClass.ListResponse buildPartial() {
        contracts.v1.ListResponseOuterClass.ListResponse result = new contracts.v1.ListResponseOuterClass.ListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (paginationBuilder_ == null) {
          result.pagination_ = pagination_;
        } else {
          result.pagination_ = paginationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof contracts.v1.ListResponseOuterClass.ListResponse) {
          return mergeFrom((contracts.v1.ListResponseOuterClass.ListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(contracts.v1.ListResponseOuterClass.ListResponse other) {
        if (other == contracts.v1.ListResponseOuterClass.ListResponse.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasPagination()) {
          mergePagination(other.getPagination());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        contracts.v1.ListResponseOuterClass.ListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (contracts.v1.ListResponseOuterClass.ListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.Any> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<com.google.protobuf.Any>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public java.util.List<com.google.protobuf.Any> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public com.google.protobuf.Any getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder setItems(
          int index, com.google.protobuf.Any value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder setItems(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder addItems(com.google.protobuf.Any value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder addItems(
          int index, com.google.protobuf.Any value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder addItems(
          com.google.protobuf.Any.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder addItems(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public com.google.protobuf.Any.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public com.google.protobuf.Any.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public com.google.protobuf.Any.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any items = 1;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private contracts.v1.PaginationOuterClass.Pagination pagination_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          contracts.v1.PaginationOuterClass.Pagination, contracts.v1.PaginationOuterClass.Pagination.Builder, contracts.v1.PaginationOuterClass.PaginationOrBuilder> paginationBuilder_;
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public boolean hasPagination() {
        return paginationBuilder_ != null || pagination_ != null;
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public contracts.v1.PaginationOuterClass.Pagination getPagination() {
        if (paginationBuilder_ == null) {
          return pagination_ == null ? contracts.v1.PaginationOuterClass.Pagination.getDefaultInstance() : pagination_;
        } else {
          return paginationBuilder_.getMessage();
        }
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public Builder setPagination(contracts.v1.PaginationOuterClass.Pagination value) {
        if (paginationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pagination_ = value;
          onChanged();
        } else {
          paginationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public Builder setPagination(
          contracts.v1.PaginationOuterClass.Pagination.Builder builderForValue) {
        if (paginationBuilder_ == null) {
          pagination_ = builderForValue.build();
          onChanged();
        } else {
          paginationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public Builder mergePagination(contracts.v1.PaginationOuterClass.Pagination value) {
        if (paginationBuilder_ == null) {
          if (pagination_ != null) {
            pagination_ =
              contracts.v1.PaginationOuterClass.Pagination.newBuilder(pagination_).mergeFrom(value).buildPartial();
          } else {
            pagination_ = value;
          }
          onChanged();
        } else {
          paginationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public Builder clearPagination() {
        if (paginationBuilder_ == null) {
          pagination_ = null;
          onChanged();
        } else {
          pagination_ = null;
          paginationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public contracts.v1.PaginationOuterClass.Pagination.Builder getPaginationBuilder() {
        
        onChanged();
        return getPaginationFieldBuilder().getBuilder();
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      public contracts.v1.PaginationOuterClass.PaginationOrBuilder getPaginationOrBuilder() {
        if (paginationBuilder_ != null) {
          return paginationBuilder_.getMessageOrBuilder();
        } else {
          return pagination_ == null ?
              contracts.v1.PaginationOuterClass.Pagination.getDefaultInstance() : pagination_;
        }
      }
      /**
       * <code>.contracts.v1.Pagination pagination = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          contracts.v1.PaginationOuterClass.Pagination, contracts.v1.PaginationOuterClass.Pagination.Builder, contracts.v1.PaginationOuterClass.PaginationOrBuilder> 
          getPaginationFieldBuilder() {
        if (paginationBuilder_ == null) {
          paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              contracts.v1.PaginationOuterClass.Pagination, contracts.v1.PaginationOuterClass.Pagination.Builder, contracts.v1.PaginationOuterClass.PaginationOrBuilder>(
                  getPagination(),
                  getParentForChildren(),
                  isClean());
          pagination_ = null;
        }
        return paginationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:contracts.v1.ListResponse)
    }

    // @@protoc_insertion_point(class_scope:contracts.v1.ListResponse)
    private static final contracts.v1.ListResponseOuterClass.ListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new contracts.v1.ListResponseOuterClass.ListResponse();
    }

    public static contracts.v1.ListResponseOuterClass.ListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListResponse>() {
      @java.lang.Override
      public ListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public contracts.v1.ListResponseOuterClass.ListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contracts_v1_ListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contracts_v1_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n contracts.v1/list_response.proto\022\014cont" +
      "racts.v1\032\035contracts.v1/pagination.proto\032" +
      "\031google/protobuf/any.proto\"a\n\014ListRespon" +
      "se\022#\n\005items\030\001 \003(\0132\024.google.protobuf.Any\022" +
      ",\n\npagination\030\002 \001(\0132\030.contracts.v1.Pagin" +
      "ationB]Z?github.com/estafette/estafette-" +
      "ci-contracts-golang/contracts_v1\252\002\031Estaf" +
      "ette.CI.Contracts.V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          contracts.v1.PaginationOuterClass.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_contracts_v1_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contracts_v1_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contracts_v1_ListResponse_descriptor,
        new java.lang.String[] { "Items", "Pagination", });
    contracts.v1.PaginationOuterClass.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
