// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/release.proto

package contracts.v1;

public final class ReleaseOuterClass {
  private ReleaseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReleaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:contracts.v1.Release)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string action = 2;</code>
     */
    java.lang.String getAction();
    /**
     * <code>string action = 2;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string repo_source = 4;</code>
     */
    java.lang.String getRepoSource();
    /**
     * <code>string repo_source = 4;</code>
     */
    com.google.protobuf.ByteString
        getRepoSourceBytes();

    /**
     * <code>string repo_owner = 5;</code>
     */
    java.lang.String getRepoOwner();
    /**
     * <code>string repo_owner = 5;</code>
     */
    com.google.protobuf.ByteString
        getRepoOwnerBytes();

    /**
     * <code>string release_version = 6;</code>
     */
    java.lang.String getReleaseVersion();
    /**
     * <code>string release_version = 6;</code>
     */
    com.google.protobuf.ByteString
        getReleaseVersionBytes();

    /**
     * <code>string release_status = 7;</code>
     */
    java.lang.String getReleaseStatus();
    /**
     * <code>string release_status = 7;</code>
     */
    com.google.protobuf.ByteString
        getReleaseStatusBytes();

    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent> 
        getEventsList();
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    manifest.v1.EstafetteEventOuterClass.EstafetteEvent getEvents(int index);
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    java.util.List<? extends manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder getEventsOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    boolean hasInsertedAt();
    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    com.google.protobuf.Timestamp getInsertedAt();
    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getInsertedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    boolean hasDuration();
    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    com.google.protobuf.Duration getDuration();
    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    com.google.protobuf.DurationOrBuilder getDurationOrBuilder();
  }
  /**
   * Protobuf type {@code contracts.v1.Release}
   */
  public  static final class Release extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:contracts.v1.Release)
      ReleaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Release.newBuilder() to construct.
    private Release(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Release() {
      name_ = "";
      action_ = "";
      id_ = "";
      repoSource_ = "";
      repoOwner_ = "";
      releaseVersion_ = "";
      releaseStatus_ = "";
      events_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Release(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              repoSource_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              repoOwner_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              releaseVersion_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              releaseStatus_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                events_ = new java.util.ArrayList<manifest.v1.EstafetteEventOuterClass.EstafetteEvent>();
                mutable_bitField0_ |= 0x00000080;
              }
              events_.add(
                  input.readMessage(manifest.v1.EstafetteEventOuterClass.EstafetteEvent.parser(), extensionRegistry));
              break;
            }
            case 74: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (insertedAt_ != null) {
                subBuilder = insertedAt_.toBuilder();
              }
              insertedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(insertedAt_);
                insertedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updatedAt_ != null) {
                subBuilder = updatedAt_.toBuilder();
              }
              updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updatedAt_);
                updatedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 90: {
              com.google.protobuf.Duration.Builder subBuilder = null;
              if (duration_ != null) {
                subBuilder = duration_.toBuilder();
              }
              duration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(duration_);
                duration_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contracts.v1.ReleaseOuterClass.internal_static_contracts_v1_Release_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contracts.v1.ReleaseOuterClass.internal_static_contracts_v1_Release_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              contracts.v1.ReleaseOuterClass.Release.class, contracts.v1.ReleaseOuterClass.Release.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 2;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_SOURCE_FIELD_NUMBER = 4;
    private volatile java.lang.Object repoSource_;
    /**
     * <code>string repo_source = 4;</code>
     */
    public java.lang.String getRepoSource() {
      java.lang.Object ref = repoSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoSource_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_source = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRepoSourceBytes() {
      java.lang.Object ref = repoSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPO_OWNER_FIELD_NUMBER = 5;
    private volatile java.lang.Object repoOwner_;
    /**
     * <code>string repo_owner = 5;</code>
     */
    public java.lang.String getRepoOwner() {
      java.lang.Object ref = repoOwner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repoOwner_ = s;
        return s;
      }
    }
    /**
     * <code>string repo_owner = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRepoOwnerBytes() {
      java.lang.Object ref = repoOwner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repoOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEASE_VERSION_FIELD_NUMBER = 6;
    private volatile java.lang.Object releaseVersion_;
    /**
     * <code>string release_version = 6;</code>
     */
    public java.lang.String getReleaseVersion() {
      java.lang.Object ref = releaseVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        releaseVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string release_version = 6;</code>
     */
    public com.google.protobuf.ByteString
        getReleaseVersionBytes() {
      java.lang.Object ref = releaseVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        releaseVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RELEASE_STATUS_FIELD_NUMBER = 7;
    private volatile java.lang.Object releaseStatus_;
    /**
     * <code>string release_status = 7;</code>
     */
    public java.lang.String getReleaseStatus() {
      java.lang.Object ref = releaseStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        releaseStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string release_status = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReleaseStatusBytes() {
      java.lang.Object ref = releaseStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        releaseStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTS_FIELD_NUMBER = 8;
    private java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent> events_;
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    public java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    public java.util.List<? extends manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    public manifest.v1.EstafetteEventOuterClass.EstafetteEvent getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
     */
    public manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    public static final int INSERTED_AT_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp insertedAt_;
    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    public boolean hasInsertedAt() {
      return insertedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    public com.google.protobuf.Timestamp getInsertedAt() {
      return insertedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getInsertedAtOrBuilder() {
      return getInsertedAt();
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 10;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return getUpdatedAt();
    }

    public static final int DURATION_FIELD_NUMBER = 11;
    private com.google.protobuf.Duration duration_;
    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    public boolean hasDuration() {
      return duration_ != null;
    }
    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    public com.google.protobuf.Duration getDuration() {
      return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
    }
    /**
     * <code>.google.protobuf.Duration duration = 11;</code>
     */
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      return getDuration();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
      if (!getRepoSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, repoSource_);
      }
      if (!getRepoOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, repoOwner_);
      }
      if (!getReleaseVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, releaseVersion_);
      }
      if (!getReleaseStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, releaseStatus_);
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(8, events_.get(i));
      }
      if (insertedAt_ != null) {
        output.writeMessage(9, getInsertedAt());
      }
      if (updatedAt_ != null) {
        output.writeMessage(10, getUpdatedAt());
      }
      if (duration_ != null) {
        output.writeMessage(11, getDuration());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      if (!getRepoSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, repoSource_);
      }
      if (!getRepoOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, repoOwner_);
      }
      if (!getReleaseVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, releaseVersion_);
      }
      if (!getReleaseStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, releaseStatus_);
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, events_.get(i));
      }
      if (insertedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getInsertedAt());
      }
      if (updatedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getUpdatedAt());
      }
      if (duration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getDuration());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof contracts.v1.ReleaseOuterClass.Release)) {
        return super.equals(obj);
      }
      contracts.v1.ReleaseOuterClass.Release other = (contracts.v1.ReleaseOuterClass.Release) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getAction()
          .equals(other.getAction());
      result = result && getId()
          .equals(other.getId());
      result = result && getRepoSource()
          .equals(other.getRepoSource());
      result = result && getRepoOwner()
          .equals(other.getRepoOwner());
      result = result && getReleaseVersion()
          .equals(other.getReleaseVersion());
      result = result && getReleaseStatus()
          .equals(other.getReleaseStatus());
      result = result && getEventsList()
          .equals(other.getEventsList());
      result = result && (hasInsertedAt() == other.hasInsertedAt());
      if (hasInsertedAt()) {
        result = result && getInsertedAt()
            .equals(other.getInsertedAt());
      }
      result = result && (hasUpdatedAt() == other.hasUpdatedAt());
      if (hasUpdatedAt()) {
        result = result && getUpdatedAt()
            .equals(other.getUpdatedAt());
      }
      result = result && (hasDuration() == other.hasDuration());
      if (hasDuration()) {
        result = result && getDuration()
            .equals(other.getDuration());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + REPO_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getRepoSource().hashCode();
      hash = (37 * hash) + REPO_OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getRepoOwner().hashCode();
      hash = (37 * hash) + RELEASE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseVersion().hashCode();
      hash = (37 * hash) + RELEASE_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseStatus().hashCode();
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      if (hasInsertedAt()) {
        hash = (37 * hash) + INSERTED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getInsertedAt().hashCode();
      }
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      if (hasDuration()) {
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static contracts.v1.ReleaseOuterClass.Release parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(contracts.v1.ReleaseOuterClass.Release prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contracts.v1.Release}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:contracts.v1.Release)
        contracts.v1.ReleaseOuterClass.ReleaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return contracts.v1.ReleaseOuterClass.internal_static_contracts_v1_Release_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return contracts.v1.ReleaseOuterClass.internal_static_contracts_v1_Release_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                contracts.v1.ReleaseOuterClass.Release.class, contracts.v1.ReleaseOuterClass.Release.Builder.class);
      }

      // Construct using contracts.v1.ReleaseOuterClass.Release.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        action_ = "";

        id_ = "";

        repoSource_ = "";

        repoOwner_ = "";

        releaseVersion_ = "";

        releaseStatus_ = "";

        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          eventsBuilder_.clear();
        }
        if (insertedAtBuilder_ == null) {
          insertedAt_ = null;
        } else {
          insertedAt_ = null;
          insertedAtBuilder_ = null;
        }
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }
        if (durationBuilder_ == null) {
          duration_ = null;
        } else {
          duration_ = null;
          durationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return contracts.v1.ReleaseOuterClass.internal_static_contracts_v1_Release_descriptor;
      }

      @java.lang.Override
      public contracts.v1.ReleaseOuterClass.Release getDefaultInstanceForType() {
        return contracts.v1.ReleaseOuterClass.Release.getDefaultInstance();
      }

      @java.lang.Override
      public contracts.v1.ReleaseOuterClass.Release build() {
        contracts.v1.ReleaseOuterClass.Release result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public contracts.v1.ReleaseOuterClass.Release buildPartial() {
        contracts.v1.ReleaseOuterClass.Release result = new contracts.v1.ReleaseOuterClass.Release(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.action_ = action_;
        result.id_ = id_;
        result.repoSource_ = repoSource_;
        result.repoOwner_ = repoOwner_;
        result.releaseVersion_ = releaseVersion_;
        result.releaseStatus_ = releaseStatus_;
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        if (insertedAtBuilder_ == null) {
          result.insertedAt_ = insertedAt_;
        } else {
          result.insertedAt_ = insertedAtBuilder_.build();
        }
        if (updatedAtBuilder_ == null) {
          result.updatedAt_ = updatedAt_;
        } else {
          result.updatedAt_ = updatedAtBuilder_.build();
        }
        if (durationBuilder_ == null) {
          result.duration_ = duration_;
        } else {
          result.duration_ = durationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof contracts.v1.ReleaseOuterClass.Release) {
          return mergeFrom((contracts.v1.ReleaseOuterClass.Release)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(contracts.v1.ReleaseOuterClass.Release other) {
        if (other == contracts.v1.ReleaseOuterClass.Release.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getRepoSource().isEmpty()) {
          repoSource_ = other.repoSource_;
          onChanged();
        }
        if (!other.getRepoOwner().isEmpty()) {
          repoOwner_ = other.repoOwner_;
          onChanged();
        }
        if (!other.getReleaseVersion().isEmpty()) {
          releaseVersion_ = other.releaseVersion_;
          onChanged();
        }
        if (!other.getReleaseStatus().isEmpty()) {
          releaseStatus_ = other.releaseStatus_;
          onChanged();
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000080);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        if (other.hasInsertedAt()) {
          mergeInsertedAt(other.getInsertedAt());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        if (other.hasDuration()) {
          mergeDuration(other.getDuration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        contracts.v1.ReleaseOuterClass.Release parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (contracts.v1.ReleaseOuterClass.Release) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 2;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 2;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 2;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 2;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 2;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoSource_ = "";
      /**
       * <code>string repo_source = 4;</code>
       */
      public java.lang.String getRepoSource() {
        java.lang.Object ref = repoSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_source = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRepoSourceBytes() {
        java.lang.Object ref = repoSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_source = 4;</code>
       */
      public Builder setRepoSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_source = 4;</code>
       */
      public Builder clearRepoSource() {
        
        repoSource_ = getDefaultInstance().getRepoSource();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_source = 4;</code>
       */
      public Builder setRepoSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object repoOwner_ = "";
      /**
       * <code>string repo_owner = 5;</code>
       */
      public java.lang.String getRepoOwner() {
        java.lang.Object ref = repoOwner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repoOwner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo_owner = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRepoOwnerBytes() {
        java.lang.Object ref = repoOwner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repoOwner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo_owner = 5;</code>
       */
      public Builder setRepoOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        repoOwner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string repo_owner = 5;</code>
       */
      public Builder clearRepoOwner() {
        
        repoOwner_ = getDefaultInstance().getRepoOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string repo_owner = 5;</code>
       */
      public Builder setRepoOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        repoOwner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object releaseVersion_ = "";
      /**
       * <code>string release_version = 6;</code>
       */
      public java.lang.String getReleaseVersion() {
        java.lang.Object ref = releaseVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          releaseVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string release_version = 6;</code>
       */
      public com.google.protobuf.ByteString
          getReleaseVersionBytes() {
        java.lang.Object ref = releaseVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          releaseVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string release_version = 6;</code>
       */
      public Builder setReleaseVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        releaseVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string release_version = 6;</code>
       */
      public Builder clearReleaseVersion() {
        
        releaseVersion_ = getDefaultInstance().getReleaseVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string release_version = 6;</code>
       */
      public Builder setReleaseVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        releaseVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object releaseStatus_ = "";
      /**
       * <code>string release_status = 7;</code>
       */
      public java.lang.String getReleaseStatus() {
        java.lang.Object ref = releaseStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          releaseStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string release_status = 7;</code>
       */
      public com.google.protobuf.ByteString
          getReleaseStatusBytes() {
        java.lang.Object ref = releaseStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          releaseStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string release_status = 7;</code>
       */
      public Builder setReleaseStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        releaseStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string release_status = 7;</code>
       */
      public Builder clearReleaseStatus() {
        
        releaseStatus_ = getDefaultInstance().getReleaseStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string release_status = 7;</code>
       */
      public Builder setReleaseStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        releaseStatus_ = value;
        onChanged();
        return this;
      }

      private java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          events_ = new java.util.ArrayList<manifest.v1.EstafetteEventOuterClass.EstafetteEvent>(events_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          manifest.v1.EstafetteEventOuterClass.EstafetteEvent, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder, manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public manifest.v1.EstafetteEventOuterClass.EstafetteEvent getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder setEvents(
          int index, manifest.v1.EstafetteEventOuterClass.EstafetteEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder setEvents(
          int index, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder addEvents(manifest.v1.EstafetteEventOuterClass.EstafetteEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder addEvents(
          int index, manifest.v1.EstafetteEventOuterClass.EstafetteEvent value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder addEvents(
          manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder addEvents(
          int index, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends manifest.v1.EstafetteEventOuterClass.EstafetteEvent> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public java.util.List<? extends manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            manifest.v1.EstafetteEventOuterClass.EstafetteEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.getDefaultInstance());
      }
      /**
       * <code>repeated .manifest.v1.EstafetteEvent events = 8;</code>
       */
      public java.util.List<manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          manifest.v1.EstafetteEventOuterClass.EstafetteEvent, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder, manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              manifest.v1.EstafetteEventOuterClass.EstafetteEvent, manifest.v1.EstafetteEventOuterClass.EstafetteEvent.Builder, manifest.v1.EstafetteEventOuterClass.EstafetteEventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }

      private com.google.protobuf.Timestamp insertedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> insertedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public boolean hasInsertedAt() {
        return insertedAtBuilder_ != null || insertedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public com.google.protobuf.Timestamp getInsertedAt() {
        if (insertedAtBuilder_ == null) {
          return insertedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : insertedAt_;
        } else {
          return insertedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public Builder setInsertedAt(com.google.protobuf.Timestamp value) {
        if (insertedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          insertedAt_ = value;
          onChanged();
        } else {
          insertedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public Builder setInsertedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (insertedAtBuilder_ == null) {
          insertedAt_ = builderForValue.build();
          onChanged();
        } else {
          insertedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public Builder mergeInsertedAt(com.google.protobuf.Timestamp value) {
        if (insertedAtBuilder_ == null) {
          if (insertedAt_ != null) {
            insertedAt_ =
              com.google.protobuf.Timestamp.newBuilder(insertedAt_).mergeFrom(value).buildPartial();
          } else {
            insertedAt_ = value;
          }
          onChanged();
        } else {
          insertedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public Builder clearInsertedAt() {
        if (insertedAtBuilder_ == null) {
          insertedAt_ = null;
          onChanged();
        } else {
          insertedAt_ = null;
          insertedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getInsertedAtBuilder() {
        
        onChanged();
        return getInsertedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getInsertedAtOrBuilder() {
        if (insertedAtBuilder_ != null) {
          return insertedAtBuilder_.getMessageOrBuilder();
        } else {
          return insertedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : insertedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp inserted_at = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getInsertedAtFieldBuilder() {
        if (insertedAtBuilder_ == null) {
          insertedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getInsertedAt(),
                  getParentForChildren(),
                  isClean());
          insertedAt_ = null;
        }
        return insertedAtBuilder_;
      }

      private com.google.protobuf.Timestamp updatedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public boolean hasUpdatedAt() {
        return updatedAtBuilder_ != null || updatedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (updatedAt_ != null) {
            updatedAt_ =
              com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
          } else {
            updatedAt_ = value;
          }
          onChanged();
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public Builder clearUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
          onChanged();
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }

      private com.google.protobuf.Duration duration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public boolean hasDuration() {
        return durationBuilder_ != null || duration_ != null;
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public com.google.protobuf.Duration getDuration() {
        if (durationBuilder_ == null) {
          return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
        } else {
          return durationBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public Builder setDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          duration_ = value;
          onChanged();
        } else {
          durationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public Builder setDuration(
          com.google.protobuf.Duration.Builder builderForValue) {
        if (durationBuilder_ == null) {
          duration_ = builderForValue.build();
          onChanged();
        } else {
          durationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public Builder mergeDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (duration_ != null) {
            duration_ =
              com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
          } else {
            duration_ = value;
          }
          onChanged();
        } else {
          durationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public Builder clearDuration() {
        if (durationBuilder_ == null) {
          duration_ = null;
          onChanged();
        } else {
          duration_ = null;
          durationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public com.google.protobuf.Duration.Builder getDurationBuilder() {
        
        onChanged();
        return getDurationFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
        if (durationBuilder_ != null) {
          return durationBuilder_.getMessageOrBuilder();
        } else {
          return duration_ == null ?
              com.google.protobuf.Duration.getDefaultInstance() : duration_;
        }
      }
      /**
       * <code>.google.protobuf.Duration duration = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
          getDurationFieldBuilder() {
        if (durationBuilder_ == null) {
          durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                  getDuration(),
                  getParentForChildren(),
                  isClean());
          duration_ = null;
        }
        return durationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:contracts.v1.Release)
    }

    // @@protoc_insertion_point(class_scope:contracts.v1.Release)
    private static final contracts.v1.ReleaseOuterClass.Release DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new contracts.v1.ReleaseOuterClass.Release();
    }

    public static contracts.v1.ReleaseOuterClass.Release getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Release>
        PARSER = new com.google.protobuf.AbstractParser<Release>() {
      @java.lang.Override
      public Release parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Release(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Release> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Release> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public contracts.v1.ReleaseOuterClass.Release getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contracts_v1_Release_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contracts_v1_Release_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032contracts.v1/release.proto\022\014contracts." +
      "v1\032!manifest.v1/estafette_event.proto\032\037g" +
      "oogle/protobuf/timestamp.proto\032\036google/p" +
      "rotobuf/duration.proto\"\310\002\n\007Release\022\014\n\004na" +
      "me\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\023\n\013" +
      "repo_source\030\004 \001(\t\022\022\n\nrepo_owner\030\005 \001(\t\022\027\n" +
      "\017release_version\030\006 \001(\t\022\026\n\016release_status" +
      "\030\007 \001(\t\022+\n\006events\030\010 \003(\0132\033.manifest.v1.Est" +
      "afetteEvent\022/\n\013inserted_at\030\t \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022.\n\nupdated_at\030\n \001(\013" +
      "2\032.google.protobuf.Timestamp\022+\n\010duration" +
      "\030\013 \001(\0132\031.google.protobuf.DurationB]Z?git" +
      "hub.com/estafette/estafette-ci-contracts" +
      "-golang/contracts_v1\252\002\031Estafette.CI.Cont" +
      "racts.V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          manifest.v1.EstafetteEventOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        }, assigner);
    internal_static_contracts_v1_Release_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contracts_v1_Release_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contracts_v1_Release_descriptor,
        new java.lang.String[] { "Name", "Action", "Id", "RepoSource", "RepoOwner", "ReleaseVersion", "ReleaseStatus", "Events", "InsertedAt", "UpdatedAt", "Duration", });
    manifest.v1.EstafetteEventOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
