// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_pub_sub_trigger.proto

package com.estafette.ci.manifest.v1;

public interface EstafettePubSubTriggerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafettePubSubTrigger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project = 1;</code>
   */
  java.lang.String getProject();
  /**
   * <code>string project = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>string topic = 2;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
