// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_event.proto

package com.estafette.ci.manifest.v1;

public final class EstafetteEventOuterClass {
  private EstafetteEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_estafette_ci_manifest_v1_EstafetteEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_estafette_ci_manifest_v1_EstafetteEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.estafette/ci/manifest/v1/estafette_eve" +
      "nt.proto\022\030estafette.ci.manifest.v1\0323esta" +
      "fette/ci/manifest/v1/estafette_cron_even" +
      "t.proto\0325estafette/ci/manifest/v1/estafe" +
      "tte_docker_event.proto\0322estafette/ci/man" +
      "ifest/v1/estafette_git_event.proto\0325esta" +
      "fette/ci/manifest/v1/estafette_manual_ev" +
      "ent.proto\0327estafette/ci/manifest/v1/esta" +
      "fette_pipeline_event.proto\0326estafette/ci" +
      "/manifest/v1/estafette_pub_sub_event.pro" +
      "to\0326estafette/ci/manifest/v1/estafette_r" +
      "elease_event.proto\"\315\003\n\016EstafetteEvent\022B\n" +
      "\010pipeline\030\001 \001(\01320.estafette.ci.manifest." +
      "v1.EstafettePipelineEvent\022@\n\007release\030\002 \001" +
      "(\0132/.estafette.ci.manifest.v1.EstafetteR" +
      "eleaseEvent\0228\n\003git\030\003 \001(\0132+.estafette.ci." +
      "manifest.v1.EstafetteGitEvent\022>\n\006docker\030" +
      "\004 \001(\0132..estafette.ci.manifest.v1.Estafet" +
      "teDockerEvent\022:\n\004cron\030\005 \001(\0132,.estafette." +
      "ci.manifest.v1.EstafetteCronEvent\022?\n\007pub" +
      "_sub\030\006 \001(\0132..estafette.ci.manifest.v1.Es" +
      "tafettePubSubEvent\022>\n\006manual\030\007 \001(\0132..est" +
      "afette.ci.manifest.v1.EstafetteManualEve" +
      "ntBx\n\034com.estafette.ci.manifest.v1P\001Z;gi" +
      "thub.com/estafette/estafette-ci-protos-g" +
      "olang/manifest_v1\252\002\030Estafette.Ci.Manifes" +
      "t.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.estafette.ci.manifest.v1.EstafetteCronEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafetteDockerEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafetteGitEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafetteManualEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafettePipelineEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafettePubSubEventOuterClass.getDescriptor(),
          com.estafette.ci.manifest.v1.EstafetteReleaseEventOuterClass.getDescriptor(),
        });
    internal_static_estafette_ci_manifest_v1_EstafetteEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_estafette_ci_manifest_v1_EstafetteEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_estafette_ci_manifest_v1_EstafetteEvent_descriptor,
        new java.lang.String[] { "Pipeline", "Release", "Git", "Docker", "Cron", "PubSub", "Manual", });
    com.estafette.ci.manifest.v1.EstafetteCronEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafetteDockerEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafetteGitEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafetteManualEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafettePipelineEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafettePubSubEventOuterClass.getDescriptor();
    com.estafette.ci.manifest.v1.EstafetteReleaseEventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
