// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_git_trigger.proto

package com.estafette.ci.manifest.v1;

public final class EstafetteGitTriggerOuterClass {
  private EstafetteGitTriggerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_estafette_ci_manifest_v1_EstafetteGitTrigger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_estafette_ci_manifest_v1_EstafetteGitTrigger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4estafette/ci/manifest/v1/estafette_git" +
      "_trigger.proto\022\030estafette.ci.manifest.v1" +
      "\"H\n\023EstafetteGitTrigger\022\r\n\005event\030\001 \001(\t\022\022" +
      "\n\nrepository\030\002 \001(\t\022\016\n\006branch\030\003 \001(\tBx\n\034co" +
      "m.estafette.ci.manifest.v1P\001Z;github.com" +
      "/estafette/estafette-ci-protos-golang/ma" +
      "nifest_v1\252\002\030Estafette.Ci.Manifest.V1b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_estafette_ci_manifest_v1_EstafetteGitTrigger_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_estafette_ci_manifest_v1_EstafetteGitTrigger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_estafette_ci_manifest_v1_EstafetteGitTrigger_descriptor,
        new java.lang.String[] { "Event", "Repository", "Branch", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
