// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_version_params.proto

package com.estafette.ci.manifest.v1;

public final class EstafetteVersionParamsOuterClass {
  private EstafetteVersionParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_estafette_ci_manifest_v1_EstafetteVersionParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_estafette_ci_manifest_v1_EstafetteVersionParams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7estafette/ci/manifest/v1/estafette_ver" +
      "sion_params.proto\022\030estafette.ci.manifest" +
      ".v1\"R\n\026EstafetteVersionParams\022\026\n\016auto_in" +
      "crement\030\001 \001(\003\022\016\n\006branch\030\002 \001(\t\022\020\n\010revisio" +
      "n\030\003 \001(\tBx\n\034com.estafette.ci.manifest.v1P" +
      "\001Z;github.com/estafette/estafette-ci-pro" +
      "tos-golang/manifest_v1\252\002\030Estafette.Ci.Ma" +
      "nifest.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_estafette_ci_manifest_v1_EstafetteVersionParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_estafette_ci_manifest_v1_EstafetteVersionParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_estafette_ci_manifest_v1_EstafetteVersionParams_descriptor,
        new java.lang.String[] { "AutoIncrement", "Branch", "Revision", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
