// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_release.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteReleaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteRelease)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool clone_repository = 2;</code>
   */
  boolean getCloneRepository();

  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteReleaseAction actions = 3;</code>
   */
  java.util.List<com.estafette.ci.manifest.v1.EstafetteReleaseAction> 
      getActionsList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteReleaseAction actions = 3;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteReleaseAction getActions(int index);
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteReleaseAction actions = 3;</code>
   */
  int getActionsCount();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteReleaseAction actions = 3;</code>
   */
  java.util.List<? extends com.estafette.ci.manifest.v1.EstafetteReleaseActionOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteReleaseAction actions = 3;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteReleaseActionOrBuilder getActionsOrBuilder(
      int index);

  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteTrigger triggers = 4;</code>
   */
  java.util.List<com.estafette.ci.manifest.v1.EstafetteTrigger> 
      getTriggersList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteTrigger triggers = 4;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteTrigger getTriggers(int index);
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteTrigger triggers = 4;</code>
   */
  int getTriggersCount();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteTrigger triggers = 4;</code>
   */
  java.util.List<? extends com.estafette.ci.manifest.v1.EstafetteTriggerOrBuilder> 
      getTriggersOrBuilderList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteTrigger triggers = 4;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteTriggerOrBuilder getTriggersOrBuilder(
      int index);

  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteStage stages = 5;</code>
   */
  java.util.List<com.estafette.ci.manifest.v1.EstafetteStage> 
      getStagesList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteStage stages = 5;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteStage getStages(int index);
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteStage stages = 5;</code>
   */
  int getStagesCount();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteStage stages = 5;</code>
   */
  java.util.List<? extends com.estafette.ci.manifest.v1.EstafetteStageOrBuilder> 
      getStagesOrBuilderList();
  /**
   * <code>repeated .estafette.ci.manifest.v1.EstafetteStage stages = 5;</code>
   */
  com.estafette.ci.manifest.v1.EstafetteStageOrBuilder getStagesOrBuilder(
      int index);
}
