// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_custom_version.proto

package com.estafette.ci.manifest.v1;

public final class EstafetteCustomVersionOuterClass {
  private EstafetteCustomVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_estafette_ci_manifest_v1_EstafetteCustomVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_estafette_ci_manifest_v1_EstafetteCustomVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7estafette/ci/manifest/v1/estafette_cus" +
      "tom_version.proto\022\030estafette.ci.manifest" +
      ".v1\"0\n\026EstafetteCustomVersion\022\026\n\016label_t" +
      "emplate\030\001 \001(\tBx\n\034com.estafette.ci.manife" +
      "st.v1P\001Z;github.com/estafette/estafette-" +
      "ci-protos-golang/manifest_v1\252\002\030Estafette" +
      ".Ci.Manifest.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_estafette_ci_manifest_v1_EstafetteCustomVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_estafette_ci_manifest_v1_EstafetteCustomVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_estafette_ci_manifest_v1_EstafetteCustomVersion_descriptor,
        new java.lang.String[] { "LabelTemplate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
