// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_release_trigger.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteReleaseTriggerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteReleaseTrigger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event = 1;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string target = 4;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 4;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
