// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_trigger_build_action.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteTriggerBuildActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteTriggerBuildAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string branch = 1;</code>
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 1;</code>
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
