// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/credential_config.proto

package com.estafette.ci.contracts.v1;

public interface CredentialConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.contracts.v1.CredentialConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; additional_properties = 3;</code>
   */
  int getAdditionalPropertiesCount();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; additional_properties = 3;</code>
   */
  boolean containsAdditionalProperties(
      java.lang.String key);
  /**
   * Use {@link #getAdditionalPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getAdditionalProperties();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; additional_properties = 3;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Any>
  getAdditionalPropertiesMap();
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; additional_properties = 3;</code>
   */

  com.google.protobuf.Any getAdditionalPropertiesOrDefault(
      java.lang.String key,
      com.google.protobuf.Any defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; additional_properties = 3;</code>
   */

  com.google.protobuf.Any getAdditionalPropertiesOrThrow(
      java.lang.String key);
}
