// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/pagination.proto

package com.estafette.ci.contracts.v1;

public interface PaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.contracts.v1.Pagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 page = 1;</code>
   */
  long getPage();

  /**
   * <code>int64 size = 2;</code>
   */
  long getSize();

  /**
   * <code>int64 total_pages = 3;</code>
   */
  long getTotalPages();

  /**
   * <code>int64 total_items = 4;</code>
   */
  long getTotalItems();
}
