// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_docker_trigger.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteDockerTriggerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteDockerTrigger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event = 1;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>string image = 2;</code>
   */
  java.lang.String getImage();
  /**
   * <code>string image = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string tag = 3;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 3;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
