// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_stage.proto

package com.estafette.ci.manifest.v1;

/**
 * Protobuf type {@code estafette.ci.manifest.v1.EstafetteStage}
 */
public  final class EstafetteStage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:estafette.ci.manifest.v1.EstafetteStage)
    EstafetteStageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EstafetteStage.newBuilder() to construct.
  private EstafetteStage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EstafetteStage() {
    name_ = "";
    containerImage_ = "";
    shell_ = "";
    workingDirectory_ = "";
    commands_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    when_ = "";
    autoInjected_ = false;
    retries_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EstafetteStage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            containerImage_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            shell_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            workingDirectory_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              commands_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            commands_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            when_ = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              envVars_ = com.google.protobuf.MapField.newMapField(
                  EnvVarsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            envVars__ = input.readMessage(
                EnvVarsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            envVars_.getMutableMap().put(
                envVars__.getKey(), envVars__.getValue());
            break;
          }
          case 64: {

            autoInjected_ = input.readBool();
            break;
          }
          case 72: {

            retries_ = input.readInt64();
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              customProperties_ = com.google.protobuf.MapField.newMapField(
                  CustomPropertiesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000200;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
            customProperties__ = input.readMessage(
                CustomPropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            customProperties_.getMutableMap().put(
                customProperties__.getKey(), customProperties__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        commands_ = commands_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetEnvVars();
      case 10:
        return internalGetCustomProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.estafette.ci.manifest.v1.EstafetteStage.class, com.estafette.ci.manifest.v1.EstafetteStage.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTAINER_IMAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object containerImage_;
  /**
   * <code>string container_image = 2;</code>
   */
  public java.lang.String getContainerImage() {
    java.lang.Object ref = containerImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      containerImage_ = s;
      return s;
    }
  }
  /**
   * <code>string container_image = 2;</code>
   */
  public com.google.protobuf.ByteString
      getContainerImageBytes() {
    java.lang.Object ref = containerImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      containerImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHELL_FIELD_NUMBER = 3;
  private volatile java.lang.Object shell_;
  /**
   * <code>string shell = 3;</code>
   */
  public java.lang.String getShell() {
    java.lang.Object ref = shell_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shell_ = s;
      return s;
    }
  }
  /**
   * <code>string shell = 3;</code>
   */
  public com.google.protobuf.ByteString
      getShellBytes() {
    java.lang.Object ref = shell_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shell_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKING_DIRECTORY_FIELD_NUMBER = 4;
  private volatile java.lang.Object workingDirectory_;
  /**
   * <code>string working_directory = 4;</code>
   */
  public java.lang.String getWorkingDirectory() {
    java.lang.Object ref = workingDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workingDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>string working_directory = 4;</code>
   */
  public com.google.protobuf.ByteString
      getWorkingDirectoryBytes() {
    java.lang.Object ref = workingDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workingDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMANDS_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList commands_;
  /**
   * <code>repeated string commands = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCommandsList() {
    return commands_;
  }
  /**
   * <code>repeated string commands = 5;</code>
   */
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <code>repeated string commands = 5;</code>
   */
  public java.lang.String getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <code>repeated string commands = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCommandsBytes(int index) {
    return commands_.getByteString(index);
  }

  public static final int WHEN_FIELD_NUMBER = 6;
  private volatile java.lang.Object when_;
  /**
   * <code>string when = 6;</code>
   */
  public java.lang.String getWhen() {
    java.lang.Object ref = when_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      when_ = s;
      return s;
    }
  }
  /**
   * <code>string when = 6;</code>
   */
  public com.google.protobuf.ByteString
      getWhenBytes() {
    java.lang.Object ref = when_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      when_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENV_VARS_FIELD_NUMBER = 7;
  private static final class EnvVarsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_EnvVarsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> envVars_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetEnvVars() {
    if (envVars_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EnvVarsDefaultEntryHolder.defaultEntry);
    }
    return envVars_;
  }

  public int getEnvVarsCount() {
    return internalGetEnvVars().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 7;</code>
   */

  public boolean containsEnvVars(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetEnvVars().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEnvVarsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getEnvVars() {
    return getEnvVarsMap();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 7;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getEnvVarsMap() {
    return internalGetEnvVars().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 7;</code>
   */

  public java.lang.String getEnvVarsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnvVars().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 7;</code>
   */

  public java.lang.String getEnvVarsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnvVars().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int AUTO_INJECTED_FIELD_NUMBER = 8;
  private boolean autoInjected_;
  /**
   * <code>bool auto_injected = 8;</code>
   */
  public boolean getAutoInjected() {
    return autoInjected_;
  }

  public static final int RETRIES_FIELD_NUMBER = 9;
  private long retries_;
  /**
   * <code>int64 retries = 9;</code>
   */
  public long getRetries() {
    return retries_;
  }

  public static final int CUSTOM_PROPERTIES_FIELD_NUMBER = 10;
  private static final class CustomPropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.Any> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_CustomPropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.protobuf.Any.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.Any> customProperties_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
  internalGetCustomProperties() {
    if (customProperties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CustomPropertiesDefaultEntryHolder.defaultEntry);
    }
    return customProperties_;
  }

  public int getCustomPropertiesCount() {
    return internalGetCustomProperties().getMap().size();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
   */

  public boolean containsCustomProperties(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetCustomProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCustomPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.Any> getCustomProperties() {
    return getCustomPropertiesMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
   */

  public java.util.Map<java.lang.String, com.google.protobuf.Any> getCustomPropertiesMap() {
    return internalGetCustomProperties().getMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
   */

  public com.google.protobuf.Any getCustomPropertiesOrDefault(
      java.lang.String key,
      com.google.protobuf.Any defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.Any> map =
        internalGetCustomProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
   */

  public com.google.protobuf.Any getCustomPropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.protobuf.Any> map =
        internalGetCustomProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getContainerImageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, containerImage_);
    }
    if (!getShellBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, shell_);
    }
    if (!getWorkingDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, workingDirectory_);
    }
    for (int i = 0; i < commands_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, commands_.getRaw(i));
    }
    if (!getWhenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, when_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEnvVars(),
        EnvVarsDefaultEntryHolder.defaultEntry,
        7);
    if (autoInjected_ != false) {
      output.writeBool(8, autoInjected_);
    }
    if (retries_ != 0L) {
      output.writeInt64(9, retries_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCustomProperties(),
        CustomPropertiesDefaultEntryHolder.defaultEntry,
        10);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getContainerImageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, containerImage_);
    }
    if (!getShellBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, shell_);
    }
    if (!getWorkingDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, workingDirectory_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < commands_.size(); i++) {
        dataSize += computeStringSizeNoTag(commands_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCommandsList().size();
    }
    if (!getWhenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, when_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetEnvVars().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      envVars__ = EnvVarsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, envVars__);
    }
    if (autoInjected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, autoInjected_);
    }
    if (retries_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, retries_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
         : internalGetCustomProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
      customProperties__ = CustomPropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, customProperties__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.estafette.ci.manifest.v1.EstafetteStage)) {
      return super.equals(obj);
    }
    com.estafette.ci.manifest.v1.EstafetteStage other = (com.estafette.ci.manifest.v1.EstafetteStage) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getContainerImage()
        .equals(other.getContainerImage());
    result = result && getShell()
        .equals(other.getShell());
    result = result && getWorkingDirectory()
        .equals(other.getWorkingDirectory());
    result = result && getCommandsList()
        .equals(other.getCommandsList());
    result = result && getWhen()
        .equals(other.getWhen());
    result = result && internalGetEnvVars().equals(
        other.internalGetEnvVars());
    result = result && (getAutoInjected()
        == other.getAutoInjected());
    result = result && (getRetries()
        == other.getRetries());
    result = result && internalGetCustomProperties().equals(
        other.internalGetCustomProperties());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CONTAINER_IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getContainerImage().hashCode();
    hash = (37 * hash) + SHELL_FIELD_NUMBER;
    hash = (53 * hash) + getShell().hashCode();
    hash = (37 * hash) + WORKING_DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getWorkingDirectory().hashCode();
    if (getCommandsCount() > 0) {
      hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getCommandsList().hashCode();
    }
    hash = (37 * hash) + WHEN_FIELD_NUMBER;
    hash = (53 * hash) + getWhen().hashCode();
    if (!internalGetEnvVars().getMap().isEmpty()) {
      hash = (37 * hash) + ENV_VARS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEnvVars().hashCode();
    }
    hash = (37 * hash) + AUTO_INJECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAutoInjected());
    hash = (37 * hash) + RETRIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRetries());
    if (!internalGetCustomProperties().getMap().isEmpty()) {
      hash = (37 * hash) + CUSTOM_PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCustomProperties().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.estafette.ci.manifest.v1.EstafetteStage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.estafette.ci.manifest.v1.EstafetteStage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code estafette.ci.manifest.v1.EstafetteStage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:estafette.ci.manifest.v1.EstafetteStage)
      com.estafette.ci.manifest.v1.EstafetteStageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetEnvVars();
        case 10:
          return internalGetCustomProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableEnvVars();
        case 10:
          return internalGetMutableCustomProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.estafette.ci.manifest.v1.EstafetteStage.class, com.estafette.ci.manifest.v1.EstafetteStage.Builder.class);
    }

    // Construct using com.estafette.ci.manifest.v1.EstafetteStage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      containerImage_ = "";

      shell_ = "";

      workingDirectory_ = "";

      commands_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      when_ = "";

      internalGetMutableEnvVars().clear();
      autoInjected_ = false;

      retries_ = 0L;

      internalGetMutableCustomProperties().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.estafette.ci.manifest.v1.EstafetteStageOuterClass.internal_static_estafette_ci_manifest_v1_EstafetteStage_descriptor;
    }

    @java.lang.Override
    public com.estafette.ci.manifest.v1.EstafetteStage getDefaultInstanceForType() {
      return com.estafette.ci.manifest.v1.EstafetteStage.getDefaultInstance();
    }

    @java.lang.Override
    public com.estafette.ci.manifest.v1.EstafetteStage build() {
      com.estafette.ci.manifest.v1.EstafetteStage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.estafette.ci.manifest.v1.EstafetteStage buildPartial() {
      com.estafette.ci.manifest.v1.EstafetteStage result = new com.estafette.ci.manifest.v1.EstafetteStage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.containerImage_ = containerImage_;
      result.shell_ = shell_;
      result.workingDirectory_ = workingDirectory_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        commands_ = commands_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.commands_ = commands_;
      result.when_ = when_;
      result.envVars_ = internalGetEnvVars();
      result.envVars_.makeImmutable();
      result.autoInjected_ = autoInjected_;
      result.retries_ = retries_;
      result.customProperties_ = internalGetCustomProperties();
      result.customProperties_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.estafette.ci.manifest.v1.EstafetteStage) {
        return mergeFrom((com.estafette.ci.manifest.v1.EstafetteStage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.estafette.ci.manifest.v1.EstafetteStage other) {
      if (other == com.estafette.ci.manifest.v1.EstafetteStage.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getContainerImage().isEmpty()) {
        containerImage_ = other.containerImage_;
        onChanged();
      }
      if (!other.getShell().isEmpty()) {
        shell_ = other.shell_;
        onChanged();
      }
      if (!other.getWorkingDirectory().isEmpty()) {
        workingDirectory_ = other.workingDirectory_;
        onChanged();
      }
      if (!other.commands_.isEmpty()) {
        if (commands_.isEmpty()) {
          commands_ = other.commands_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureCommandsIsMutable();
          commands_.addAll(other.commands_);
        }
        onChanged();
      }
      if (!other.getWhen().isEmpty()) {
        when_ = other.when_;
        onChanged();
      }
      internalGetMutableEnvVars().mergeFrom(
          other.internalGetEnvVars());
      if (other.getAutoInjected() != false) {
        setAutoInjected(other.getAutoInjected());
      }
      if (other.getRetries() != 0L) {
        setRetries(other.getRetries());
      }
      internalGetMutableCustomProperties().mergeFrom(
          other.internalGetCustomProperties());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.estafette.ci.manifest.v1.EstafetteStage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.estafette.ci.manifest.v1.EstafetteStage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object containerImage_ = "";
    /**
     * <code>string container_image = 2;</code>
     */
    public java.lang.String getContainerImage() {
      java.lang.Object ref = containerImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        containerImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string container_image = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContainerImageBytes() {
      java.lang.Object ref = containerImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string container_image = 2;</code>
     */
    public Builder setContainerImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      containerImage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string container_image = 2;</code>
     */
    public Builder clearContainerImage() {
      
      containerImage_ = getDefaultInstance().getContainerImage();
      onChanged();
      return this;
    }
    /**
     * <code>string container_image = 2;</code>
     */
    public Builder setContainerImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      containerImage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shell_ = "";
    /**
     * <code>string shell = 3;</code>
     */
    public java.lang.String getShell() {
      java.lang.Object ref = shell_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shell_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shell = 3;</code>
     */
    public com.google.protobuf.ByteString
        getShellBytes() {
      java.lang.Object ref = shell_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shell_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shell = 3;</code>
     */
    public Builder setShell(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shell_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shell = 3;</code>
     */
    public Builder clearShell() {
      
      shell_ = getDefaultInstance().getShell();
      onChanged();
      return this;
    }
    /**
     * <code>string shell = 3;</code>
     */
    public Builder setShellBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shell_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object workingDirectory_ = "";
    /**
     * <code>string working_directory = 4;</code>
     */
    public java.lang.String getWorkingDirectory() {
      java.lang.Object ref = workingDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workingDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string working_directory = 4;</code>
     */
    public com.google.protobuf.ByteString
        getWorkingDirectoryBytes() {
      java.lang.Object ref = workingDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workingDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string working_directory = 4;</code>
     */
    public Builder setWorkingDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workingDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string working_directory = 4;</code>
     */
    public Builder clearWorkingDirectory() {
      
      workingDirectory_ = getDefaultInstance().getWorkingDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>string working_directory = 4;</code>
     */
    public Builder setWorkingDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workingDirectory_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList commands_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCommandsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        commands_ = new com.google.protobuf.LazyStringArrayList(commands_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCommandsList() {
      return commands_.getUnmodifiableView();
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public java.lang.String getCommands(int index) {
      return commands_.get(index);
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommandsBytes(int index) {
      return commands_.getByteString(index);
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public Builder setCommands(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCommandsIsMutable();
      commands_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public Builder addCommands(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCommandsIsMutable();
      commands_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public Builder addAllCommands(
        java.lang.Iterable<java.lang.String> values) {
      ensureCommandsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, commands_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public Builder clearCommands() {
      commands_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 5;</code>
     */
    public Builder addCommandsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCommandsIsMutable();
      commands_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object when_ = "";
    /**
     * <code>string when = 6;</code>
     */
    public java.lang.String getWhen() {
      java.lang.Object ref = when_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        when_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string when = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWhenBytes() {
      java.lang.Object ref = when_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        when_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string when = 6;</code>
     */
    public Builder setWhen(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      when_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string when = 6;</code>
     */
    public Builder clearWhen() {
      
      when_ = getDefaultInstance().getWhen();
      onChanged();
      return this;
    }
    /**
     * <code>string when = 6;</code>
     */
    public Builder setWhenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      when_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> envVars_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEnvVars() {
      if (envVars_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EnvVarsDefaultEntryHolder.defaultEntry);
      }
      return envVars_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableEnvVars() {
      onChanged();;
      if (envVars_ == null) {
        envVars_ = com.google.protobuf.MapField.newMapField(
            EnvVarsDefaultEntryHolder.defaultEntry);
      }
      if (!envVars_.isMutable()) {
        envVars_ = envVars_.copy();
      }
      return envVars_;
    }

    public int getEnvVarsCount() {
      return internalGetEnvVars().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public boolean containsEnvVars(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetEnvVars().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEnvVarsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEnvVars() {
      return getEnvVarsMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getEnvVarsMap() {
      return internalGetEnvVars().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public java.lang.String getEnvVarsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnvVars().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public java.lang.String getEnvVarsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnvVars().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEnvVars() {
      internalGetMutableEnvVars().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public Builder removeEnvVars(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEnvVars().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableEnvVars() {
      return internalGetMutableEnvVars().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */
    public Builder putEnvVars(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEnvVars().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 7;</code>
     */

    public Builder putAllEnvVars(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableEnvVars().getMutableMap()
          .putAll(values);
      return this;
    }

    private boolean autoInjected_ ;
    /**
     * <code>bool auto_injected = 8;</code>
     */
    public boolean getAutoInjected() {
      return autoInjected_;
    }
    /**
     * <code>bool auto_injected = 8;</code>
     */
    public Builder setAutoInjected(boolean value) {
      
      autoInjected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool auto_injected = 8;</code>
     */
    public Builder clearAutoInjected() {
      
      autoInjected_ = false;
      onChanged();
      return this;
    }

    private long retries_ ;
    /**
     * <code>int64 retries = 9;</code>
     */
    public long getRetries() {
      return retries_;
    }
    /**
     * <code>int64 retries = 9;</code>
     */
    public Builder setRetries(long value) {
      
      retries_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 retries = 9;</code>
     */
    public Builder clearRetries() {
      
      retries_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> customProperties_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetCustomProperties() {
      if (customProperties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomPropertiesDefaultEntryHolder.defaultEntry);
      }
      return customProperties_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetMutableCustomProperties() {
      onChanged();;
      if (customProperties_ == null) {
        customProperties_ = com.google.protobuf.MapField.newMapField(
            CustomPropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!customProperties_.isMutable()) {
        customProperties_ = customProperties_.copy();
      }
      return customProperties_;
    }

    public int getCustomPropertiesCount() {
      return internalGetCustomProperties().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public boolean containsCustomProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCustomProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getCustomProperties() {
      return getCustomPropertiesMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getCustomPropertiesMap() {
      return internalGetCustomProperties().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public com.google.protobuf.Any getCustomPropertiesOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetCustomProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public com.google.protobuf.Any getCustomPropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetCustomProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearCustomProperties() {
      internalGetMutableCustomProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public Builder removeCustomProperties(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCustomProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any>
    getMutableCustomProperties() {
      return internalGetMutableCustomProperties().getMutableMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */
    public Builder putCustomProperties(
        java.lang.String key,
        com.google.protobuf.Any value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCustomProperties().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Any&gt; custom_properties = 10;</code>
     */

    public Builder putAllCustomProperties(
        java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
      internalGetMutableCustomProperties().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:estafette.ci.manifest.v1.EstafetteStage)
  }

  // @@protoc_insertion_point(class_scope:estafette.ci.manifest.v1.EstafetteStage)
  private static final com.estafette.ci.manifest.v1.EstafetteStage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.estafette.ci.manifest.v1.EstafetteStage();
  }

  public static com.estafette.ci.manifest.v1.EstafetteStage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EstafetteStage>
      PARSER = new com.google.protobuf.AbstractParser<EstafetteStage>() {
    @java.lang.Override
    public EstafetteStage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EstafetteStage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EstafetteStage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EstafetteStage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.estafette.ci.manifest.v1.EstafetteStage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

