// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_trigger_release_action.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteTriggerReleaseActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteTriggerReleaseAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string target = 1;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <code>string action = 2;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string version = 3;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
