// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/manifest/v1/estafette_release_event.proto

package com.estafette.ci.manifest.v1;

public interface EstafetteReleaseEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.manifest.v1.EstafetteReleaseEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string release_version = 1;</code>
   */
  java.lang.String getReleaseVersion();
  /**
   * <code>string release_version = 1;</code>
   */
  com.google.protobuf.ByteString
      getReleaseVersionBytes();

  /**
   * <code>string repo_source = 2;</code>
   */
  java.lang.String getRepoSource();
  /**
   * <code>string repo_source = 2;</code>
   */
  com.google.protobuf.ByteString
      getRepoSourceBytes();

  /**
   * <code>string repo_owner = 3;</code>
   */
  java.lang.String getRepoOwner();
  /**
   * <code>string repo_owner = 3;</code>
   */
  com.google.protobuf.ByteString
      getRepoOwnerBytes();

  /**
   * <code>string repo_name = 4;</code>
   */
  java.lang.String getRepoName();
  /**
   * <code>string repo_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getRepoNameBytes();

  /**
   * <code>string target = 5;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 5;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <code>string status = 6;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string event = 7;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 7;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();
}
