// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/build_version_config.proto

package io.estafette.ci.protos.contracts.v1;

public final class BuildVersionConfigOuterClass {
  private BuildVersionConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildVersionConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:contracts.v1.BuildVersionConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>int64 major = 2;</code>
     */
    long getMajor();

    /**
     * <code>int64 minor = 3;</code>
     */
    long getMinor();

    /**
     * <code>string patch = 4;</code>
     */
    java.lang.String getPatch();
    /**
     * <code>string patch = 4;</code>
     */
    com.google.protobuf.ByteString
        getPatchBytes();

    /**
     * <code>string label = 5;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 5;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>int64 auto_increment = 6;</code>
     */
    long getAutoIncrement();
  }
  /**
   * Protobuf type {@code contracts.v1.BuildVersionConfig}
   */
  public  static final class BuildVersionConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:contracts.v1.BuildVersionConfig)
      BuildVersionConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuildVersionConfig.newBuilder() to construct.
    private BuildVersionConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuildVersionConfig() {
      version_ = "";
      major_ = 0L;
      minor_ = 0L;
      patch_ = "";
      label_ = "";
      autoIncrement_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuildVersionConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 16: {

              major_ = input.readInt64();
              break;
            }
            case 24: {

              minor_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              patch_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 48: {

              autoIncrement_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.internal_static_contracts_v1_BuildVersionConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.internal_static_contracts_v1_BuildVersionConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.class, io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAJOR_FIELD_NUMBER = 2;
    private long major_;
    /**
     * <code>int64 major = 2;</code>
     */
    public long getMajor() {
      return major_;
    }

    public static final int MINOR_FIELD_NUMBER = 3;
    private long minor_;
    /**
     * <code>int64 minor = 3;</code>
     */
    public long getMinor() {
      return minor_;
    }

    public static final int PATCH_FIELD_NUMBER = 4;
    private volatile java.lang.Object patch_;
    /**
     * <code>string patch = 4;</code>
     */
    public java.lang.String getPatch() {
      java.lang.Object ref = patch_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patch_ = s;
        return s;
      }
    }
    /**
     * <code>string patch = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPatchBytes() {
      java.lang.Object ref = patch_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patch_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 5;
    private volatile java.lang.Object label_;
    /**
     * <code>string label = 5;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTO_INCREMENT_FIELD_NUMBER = 6;
    private long autoIncrement_;
    /**
     * <code>int64 auto_increment = 6;</code>
     */
    public long getAutoIncrement() {
      return autoIncrement_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (major_ != 0L) {
        output.writeInt64(2, major_);
      }
      if (minor_ != 0L) {
        output.writeInt64(3, minor_);
      }
      if (!getPatchBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, patch_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, label_);
      }
      if (autoIncrement_ != 0L) {
        output.writeInt64(6, autoIncrement_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (major_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, major_);
      }
      if (minor_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, minor_);
      }
      if (!getPatchBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, patch_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, label_);
      }
      if (autoIncrement_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, autoIncrement_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig)) {
        return super.equals(obj);
      }
      io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig other = (io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig) obj;

      boolean result = true;
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getMajor()
          == other.getMajor());
      result = result && (getMinor()
          == other.getMinor());
      result = result && getPatch()
          .equals(other.getPatch());
      result = result && getLabel()
          .equals(other.getLabel());
      result = result && (getAutoIncrement()
          == other.getAutoIncrement());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + MAJOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMajor());
      hash = (37 * hash) + MINOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMinor());
      hash = (37 * hash) + PATCH_FIELD_NUMBER;
      hash = (53 * hash) + getPatch().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + AUTO_INCREMENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAutoIncrement());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code contracts.v1.BuildVersionConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:contracts.v1.BuildVersionConfig)
        io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.internal_static_contracts_v1_BuildVersionConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.internal_static_contracts_v1_BuildVersionConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.class, io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.Builder.class);
      }

      // Construct using io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = "";

        major_ = 0L;

        minor_ = 0L;

        patch_ = "";

        label_ = "";

        autoIncrement_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.internal_static_contracts_v1_BuildVersionConfig_descriptor;
      }

      @java.lang.Override
      public io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig getDefaultInstanceForType() {
        return io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.getDefaultInstance();
      }

      @java.lang.Override
      public io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig build() {
        io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig buildPartial() {
        io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig result = new io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig(this);
        result.version_ = version_;
        result.major_ = major_;
        result.minor_ = minor_;
        result.patch_ = patch_;
        result.label_ = label_;
        result.autoIncrement_ = autoIncrement_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig) {
          return mergeFrom((io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig other) {
        if (other == io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getMajor() != 0L) {
          setMajor(other.getMajor());
        }
        if (other.getMinor() != 0L) {
          setMinor(other.getMinor());
        }
        if (!other.getPatch().isEmpty()) {
          patch_ = other.patch_;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (other.getAutoIncrement() != 0L) {
          setAutoIncrement(other.getAutoIncrement());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private long major_ ;
      /**
       * <code>int64 major = 2;</code>
       */
      public long getMajor() {
        return major_;
      }
      /**
       * <code>int64 major = 2;</code>
       */
      public Builder setMajor(long value) {
        
        major_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 major = 2;</code>
       */
      public Builder clearMajor() {
        
        major_ = 0L;
        onChanged();
        return this;
      }

      private long minor_ ;
      /**
       * <code>int64 minor = 3;</code>
       */
      public long getMinor() {
        return minor_;
      }
      /**
       * <code>int64 minor = 3;</code>
       */
      public Builder setMinor(long value) {
        
        minor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 minor = 3;</code>
       */
      public Builder clearMinor() {
        
        minor_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object patch_ = "";
      /**
       * <code>string patch = 4;</code>
       */
      public java.lang.String getPatch() {
        java.lang.Object ref = patch_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patch_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patch = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPatchBytes() {
        java.lang.Object ref = patch_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patch_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patch = 4;</code>
       */
      public Builder setPatch(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patch = 4;</code>
       */
      public Builder clearPatch() {
        
        patch_ = getDefaultInstance().getPatch();
        onChanged();
        return this;
      }
      /**
       * <code>string patch = 4;</code>
       */
      public Builder setPatchBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patch_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 5;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 5;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 5;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>string label = 5;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private long autoIncrement_ ;
      /**
       * <code>int64 auto_increment = 6;</code>
       */
      public long getAutoIncrement() {
        return autoIncrement_;
      }
      /**
       * <code>int64 auto_increment = 6;</code>
       */
      public Builder setAutoIncrement(long value) {
        
        autoIncrement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 auto_increment = 6;</code>
       */
      public Builder clearAutoIncrement() {
        
        autoIncrement_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:contracts.v1.BuildVersionConfig)
    }

    // @@protoc_insertion_point(class_scope:contracts.v1.BuildVersionConfig)
    private static final io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig();
    }

    public static io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildVersionConfig>
        PARSER = new com.google.protobuf.AbstractParser<BuildVersionConfig>() {
      @java.lang.Override
      public BuildVersionConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildVersionConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuildVersionConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildVersionConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.estafette.ci.protos.contracts.v1.BuildVersionConfigOuterClass.BuildVersionConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contracts_v1_BuildVersionConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contracts_v1_BuildVersionConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'contracts.v1/build_version_config.prot" +
      "o\022\014contracts.v1\"y\n\022BuildVersionConfig\022\017\n" +
      "\007version\030\001 \001(\t\022\r\n\005major\030\002 \001(\003\022\r\n\005minor\030\003" +
      " \001(\003\022\r\n\005patch\030\004 \001(\t\022\r\n\005label\030\005 \001(\t\022\026\n\016au" +
      "to_increment\030\006 \001(\003B\177\n#io.estafette.ci.pr" +
      "otos.contracts.v1Z<github.com/estafette/" +
      "estafette-ci-protos-golang/contracts_v1\252" +
      "\002\031Estafette.CI.Contracts.V1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_contracts_v1_BuildVersionConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contracts_v1_BuildVersionConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contracts_v1_BuildVersionConfig_descriptor,
        new java.lang.String[] { "Version", "Major", "Minor", "Patch", "Label", "AutoIncrement", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
