// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/git_commit.proto

package com.estafette.ci.contracts.v1;

public interface GitCommitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.contracts.v1.GitCommit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.estafette.ci.contracts.v1.GitAuthor author = 2;</code>
   */
  boolean hasAuthor();
  /**
   * <code>.estafette.ci.contracts.v1.GitAuthor author = 2;</code>
   */
  com.estafette.ci.contracts.v1.GitAuthor getAuthor();
  /**
   * <code>.estafette.ci.contracts.v1.GitAuthor author = 2;</code>
   */
  com.estafette.ci.contracts.v1.GitAuthorOrBuilder getAuthorOrBuilder();
}
