// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/pagination.proto

package com.estafette.ci.contracts.v1;

public final class PaginationOuterClass {
  private PaginationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_estafette_ci_contracts_v1_Pagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_estafette_ci_contracts_v1_Pagination_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*estafette/ci/contracts/v1/pagination.p" +
      "roto\022\031estafette.ci.contracts.v1\"R\n\nPagin" +
      "ation\022\014\n\004page\030\001 \001(\003\022\014\n\004size\030\002 \001(\003\022\023\n\013tot" +
      "al_pages\030\003 \001(\003\022\023\n\013total_items\030\004 \001(\003B{\n\035c" +
      "om.estafette.ci.contracts.v1P\001Z<github.c" +
      "om/estafette/estafette-ci-protos-golang/" +
      "contracts/v1\252\002\031Estafette.Ci.Contracts.V1" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_estafette_ci_contracts_v1_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_estafette_ci_contracts_v1_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_estafette_ci_contracts_v1_Pagination_descriptor,
        new java.lang.String[] { "Page", "Size", "TotalPages", "TotalItems", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
