// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/tail_log_line.proto

package com.estafette.ci.contracts.v1;

public interface TailLogLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:estafette.ci.contracts.v1.TailLogLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string step = 1;</code>
   */
  java.lang.String getStep();
  /**
   * <code>string step = 1;</code>
   */
  com.google.protobuf.ByteString
      getStepBytes();

  /**
   * <code>.estafette.ci.contracts.v1.BuildLogLine log_line = 2;</code>
   */
  boolean hasLogLine();
  /**
   * <code>.estafette.ci.contracts.v1.BuildLogLine log_line = 2;</code>
   */
  com.estafette.ci.contracts.v1.BuildLogLine getLogLine();
  /**
   * <code>.estafette.ci.contracts.v1.BuildLogLine log_line = 2;</code>
   */
  com.estafette.ci.contracts.v1.BuildLogLineOrBuilder getLogLineOrBuilder();

  /**
   * <code>.estafette.ci.contracts.v1.BuildLogStepDockerImage image = 3;</code>
   */
  boolean hasImage();
  /**
   * <code>.estafette.ci.contracts.v1.BuildLogStepDockerImage image = 3;</code>
   */
  com.estafette.ci.contracts.v1.BuildLogStepDockerImage getImage();
  /**
   * <code>.estafette.ci.contracts.v1.BuildLogStepDockerImage image = 3;</code>
   */
  com.estafette.ci.contracts.v1.BuildLogStepDockerImageOrBuilder getImageOrBuilder();

  /**
   * <code>.google.protobuf.Duration duration = 4;</code>
   */
  boolean hasDuration();
  /**
   * <code>.google.protobuf.Duration duration = 4;</code>
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <code>.google.protobuf.Duration duration = 4;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

  /**
   * <code>int64 exit_code = 5;</code>
   */
  long getExitCode();

  /**
   * <code>string status = 6;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool auto_injected = 7;</code>
   */
  boolean getAutoInjected();
}
